sudo: false

language: cpp

compiler: 
  - gcc
  - g++

addons:
    apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-multilib
          - gcc-5
          - g++-5
          - gcc-5-locales
          - gcc-5-multilib
          - g++-5-multilib
          - time
          - libstdc++6-5-dbg
          - lib32stdc++6-5-dbg
          - libstdc++-5-doc
          - libgcc1-dbg
          - libgomp1-dbg
          - libitm1-dbg
          - libatomic1-dbg
          - libasan2-dbg
          - liblsan0-dbg
          - libtsan0-dbg
          - libubsan0-dbg
          - libcilkrts5-dbg
          - libquadmath0-dbg
          - zlib1g-dev
          - libbz2-dev
          - libsnappy-dev

before_script:
  - export CXX=/usr/bin/gcc-5
  - export CXX=/usr/bin/g++-5
  - chmod +x unpack_rocksdb.sh
  - ./unpack_rocksdb.sh

script:
  - cd server/
  - chmod +x build.sh 
  - ./build.sh
  - chmod +x run_tests.sh
  - ./run_tests.sh

branches:
  only:
    - master

notifications:
  email: false

os:
  -linux
